/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CpStockPrice {
    }
}
declare global {
    interface HTMLCpStockPriceElement extends Components.CpStockPrice, HTMLStencilElement {
    }
    var HTMLCpStockPriceElement: {
        prototype: HTMLCpStockPriceElement;
        new (): HTMLCpStockPriceElement;
    };
    interface HTMLElementTagNameMap {
        "cp-stock-price": HTMLCpStockPriceElement;
    }
}
declare namespace LocalJSX {
    interface CpStockPrice {
    }
    interface IntrinsicElements {
        "cp-stock-price": CpStockPrice;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cp-stock-price": LocalJSX.CpStockPrice & JSXBase.HTMLAttributes<HTMLCpStockPriceElement>;
        }
    }
}
