/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CpSideDrawer {
        "open": () => Promise<void>;
        "opened": boolean;
        "sliderTitle": string;
    }
    interface CpTooltip {
        "content": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLCpSideDrawerElement extends Components.CpSideDrawer, HTMLStencilElement {
    }
    var HTMLCpSideDrawerElement: {
        prototype: HTMLCpSideDrawerElement;
        new (): HTMLCpSideDrawerElement;
    };
    interface HTMLCpTooltipElement extends Components.CpTooltip, HTMLStencilElement {
    }
    var HTMLCpTooltipElement: {
        prototype: HTMLCpTooltipElement;
        new (): HTMLCpTooltipElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "cp-side-drawer": HTMLCpSideDrawerElement;
        "cp-tooltip": HTMLCpTooltipElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface CpSideDrawer {
        "opened"?: boolean;
        "sliderTitle"?: string;
    }
    interface CpTooltip {
        "content"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "cp-side-drawer": CpSideDrawer;
        "cp-tooltip": CpTooltip;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cp-side-drawer": LocalJSX.CpSideDrawer & JSXBase.HTMLAttributes<HTMLCpSideDrawerElement>;
            "cp-tooltip": LocalJSX.CpTooltip & JSXBase.HTMLAttributes<HTMLCpTooltipElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
